// flow-typed signature: 4b51fa16fc42964f367763c42254bb2a
// flow-typed version: <<STUB>>/postcss-selector-not_v^3.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-selector-not'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-selector-not' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-selector-not/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-selector-not/dist/index.js' {
  declare module.exports: $Exports<'postcss-selector-not/dist/index'>;
}
